" replace tab by space
set tabstop=4
set expandtab
set shiftwidth=4

" Enable mouse usage
set mouse=a

" Matching options
set ignorecase

set showcmd

" Wrap text
set wrap

" Display line
set number

" Fixes common backspace problems
set backspace=indent,eol,start

" Vim's auto indentation feature does not work properly with text copied from outside of Vim. Press the <F2> key to toggle paste mode on/off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>

 " Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

